language: python

python:
 - "2.7"
sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

virtualenv:
system_site_packages: true

script:
 - travis_run_tests

after_succes:
 - travis_after_tests_success

